
export const products = [
  {
    title: "Cisne Rendidora Jumbo",
    description: "lana cisne rendidora jumbo 100% acrilico ",
    color: "lila",
    price: 200,
    stock: 150,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686195840/Lila-15020_nwn34h.png",
    category: "lanas",
  },
  {
    title: "Cisne Rendidora Jumbo",
    description: "lana cisne rendidora jumbo 100% acrilico ",
    color: "Rosa bebé",
    price: 200,
    stock: 14,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686197330/rendidoraRosa_yviu0c.png",
    category: "lanas",
  },
  {
    title: "Cisne Rendidora Jumbo",
    description: "lana cisne rendidora jumbo 100% acrilico ",
    color: "Fucsia",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686196334/rendidoraRosa_c6m5ix.png",
    category: "lanas",
  },
  {
    title: "Cisne Rendidora Jumbo",
    description: "lana cisne rendidora jumbo 100% acrilico ",
    color: "Violeta",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686197099/rendidoraVioleta_vvf35t.png",
    category: "lanas",
  },
  {
    title: "Cisne Rendidora Jumbo",
    description: "lana cisne rendidora jumbo 100% acrilico ",
    color: "Turquesa",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686196334/rendidoraTurquesa_zxgroc.png",
    category: "lanas",
  },
  {
    title: "Agujas de crochet mango de silicona ",
    description:
      "Set de agujas de crochet con mango de silicona para un mejor agarre",
    color: "",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686198346/agujasCrochetSilicona_ekpq87.png",
    category: "agujas",
  },
  {
    title: "Agujas de crochet metalicas",
    description: "Agujas de crochet metalicas",
    color: "",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686198345/agujasCrochetMetal_fjqkyf.jpg",
    category: "agujas",
  },
  {
    title: "Aguja de coser",
    description: "Agujas de coser x5 unidades",
    color: "",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686198345/agujasCoser_cnmnjv.jpg",
    category: "agujas",
  },
  {
    title: "Agujas de tejer",
    description: "Agujas para tejidos a dos agujas",
    color: "",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686198314/DosAgujas_yzk8vi.webp",
    category: "agujas",
  },
  {
    title: "Marca puntos crochet",
    description: "marcadores de punto para crochet x10 unidades",
    color: "",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686198291/marcaPuntos_w3dsjw.webp",
    category: "alfileres",
  },
  {
    title: "Alfiler de gancho",
    description: "alfileres de gancho metálicos",
    color: "",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686198345/alfileres_czzmmo.jpg",
    category: "alfileres",
  },
  {
    title: "Alfileres",
    description: "Set de alfileres x20 unidades",
    color: "",
    price: 200,
    stock: 140,
    img: "https://res.cloudinary.com/ddyhhrr0g/image/upload/v1686198264/setAlfileres_oj0sl3.jpg",
    category: "alfileres",
  },
];